### ISSUE TITLE
EXE Error!

### ISSUE THREAD

**Issue by ImInTheICU** [Mickey758/Calani-AIO#7]
When using EXE and using the proxie scrapper at the end it errors!
I;m on windows

**Comment by ImInTheICU** [comment]
```
Traceback (most recent call last):
  File "C:\Users\14794\Downloads\Calani-AIO-master\main.py", line 183, in <module>
    if not need_update: home()
  File "C:\Users\14794\Downloads\Calani-AIO-master\main.py", line 33, in home
    case "2": tools()
  File "C:\Users\14794\Downloads\Calani-AIO-master\main.py", line 169, in tools
    case "2": proxy_scrape.start()
  File "C:\Users\14794\Downloads\Calani-AIO-master\modules\tools\proxy_scrape.py", line 127, in start
    case "2": scrape()
  File "C:\Users\14794\Downloads\Calani-AIO-master\modules\tools\proxy_scrape.py", line 185, in scrape
    with open(f"Results/{Checker.time}/Scraped_Proxies.txt","w",errors="ignore") as file: file.write("\n".join(proxies))
TypeError: can only join an iterable
```

Using Source

**Comment by ImInTheICU** [comment]
I fixed ur code by doing this 
```
proxies = list(set(proxies))
```

**Comment by ImInTheICU** [comment]
Also what have you done everything feels sooo slow to run (IE ProxyChecker)
